name: Deploy Airflow DAGs to S3

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy-dags:
    runs-on: ubuntu-latest

    steps:

      # 1. Get the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Upload DAGs to S3
      - name: Upload DAGs to S3
        run: |
          aws s3 sync dags s3://real-estate-glue-knb/dags/ --delete

      # 4. Verify DAGs in S3
      - name: Verify DAGs in S3
        run: |
          aws s3 ls s3://real-estate-glue-knb/dags/

      # 5. Create plugins.zip
      - name: Create plugins.zip
        run: |
          cd plugins
          zip -r ../plugins.zip .
          cd ..

      # 6. Upload plugins.zip to S3
      - name: Upload plugins.zip to S3
        run: |
          aws s3 cp plugins.zip s3://real-estate-glue-knb/plugins.zip

      # 7. Verify plugins.zip in S3
      - name: Verify plugins.zip in S3
        run: |
          aws s3 ls s3://real-estate-glue-knb/plugins.zip

      # Upload requirements.txt to S3
      - name: Upload requirements to S3
        run: |
          aws s3 cp requirements.txt s3://real-estate-glue-knb/requirements.txt

      # Verify requirements.txt in S3
      - name: Verify requirements.txt in S3
        run: |
          aws s3 ls s3://real-estate-glue-knb/requirements.txt
          
